# -*- coding: utf-8 -*-
from pathlib import Path
path = Path('apps/web/src/components/NavBar.vue')
text = path.read_text(encoding='utf-8')
old = "const cardRedeemOpen = ref(false)\nconst cardRedeemFiles = ref<File[]>([])\nfunction openCardRedeem(){\n  if (!auth.token) { router.push('/login'); return }\n  cardRedeemOpen.value = true\n}\nfunction onCardRedeemConfirm(files: File[]){\n  cardRedeemFiles.value = files\n  console.log('Card redeem submit:', files)\n}\nfunction onCardRedeemContinue(files: File[]){\n  cardRedeemFiles.value = files\n  console.log('Card redeem continue upload:', files)\n}\n"
new = "const cardRedeemOpen = ref(false)\nconst cardRedeemFiles = ref<File[]>([])\nfunction openCardRedeem(){\n  if (!auth.token) { router.push('/login'); return }\n  cardRedeemOpen.value = true\n}\nasync function onCardRedeemConfirm(files: File[]){\n  if (!auth.token) { router.push('/login'); return }\n  if (!files.length){\n    alert('请至少上传一张兑换凭证图片');\n    return\n  }\n  try{\n    const images = await Promise.all(files.map((file) => new Promise<{ name: string; data: string }>((resolve, reject) => {\n      const reader = new FileReader()\n      reader.onload = () => {\n        if (typeof reader.result === 'string') resolve({ name: file.name, data: reader.result })\n        else reject(new Error('无法读取图片'))\n      }\n      reader.onerror = () => reject(new Error('读取图片失败'))\n      reader.readAsDataURL(file)\n    })))\n    await api.post('/api/cards/redeem', {\n      username: me.value?.nickname || (me.value as any)?.username || '',\n      email: me.value?.email || '',\n      gender: (me.value as any)?.gender || '',\n      balance: Number(me.value?.balance ?? balance.value ?? 0),\n      images\n    })\n    alert('已提交点卡兑换申请，请等待审核。')\n    cardRedeemFiles.value = []\n    cardRedeemOpen.value = false\n  }catch(err){\n    console.error(err)\n    const msg = (err as any)?.response?.data?.error\n    alert(msg ? String(msg) : '提交失败，请稍后重试')\n  }\n}\nfunction onCardRedeemContinue(files: File[]){\n  cardRedeemFiles.value = files\n}\n"
if old not in text:
    raise SystemExit('pattern not found for card redeem block')
path.write_text(text.replace(old, new), encoding='utf-8')
